title: Alienware CLI
name: alienware-wmi
type: app
base: core20
version: ':snap_version'
summary: Alienware LEDs and HDMI Control
description: |
  The `alienware-cli` application controls the LEDs and the HDMI in and out ports on an Alienware Alpha desktop machine.
  The API is based on the `alienware_wmi_control.sh` script that used to come with the SteamOS distribution of Linux for
  Alienware machines.

grade: stable
confinement: strict
issues: https://github.com/a1ecbr0wn/alienware-wmi/issues
website: https://github.com/a1ecbr0wn/alienware-wmi/tree/main/alienware_cli
icon: img/appicon-512.png
license: Apache-2.0

architectures:
  - build-on: amd64
    run-on: amd64

parts:
 awc:
    plugin: rust
    source: https://github.com/a1ecbr0wn/alienware-wmi/archive/refs/tags/:snap_version.tar.gz
    rust-path: ["alienware_cli"]

apps:
  awc:
    command: bin/awc
