title: Alienware CLI
name: alienware-wmi
type: app
base: core20
version: 'v1.0.4'
summary: Alienware LEDs and HDMI Control
description: |
  The `alienware-cli` application controls the LEDs and the HDMI in and out ports on an Alienware Alpha desktop machine.
  The API is based on the `alienware_wmi_control.sh` script that used to come with the SteamOS distribution of Linux for
  Alienware machines.

grade: stable
confinement: strict
issues: https://github.com/a1ecbr0wn/alienware-wmi/issues
website: https://github.com/a1ecbr0wn/alienware-wmi/tree/main/alienware_cli
icon: img/appicon-512.png
license: Apache-2.0

architectures:
  - build-on: amd64
    run-on: amd64

slots:
  alienware:
    interface: custom-device
    custom-device: alienware-wmi
    files:
      write:
        - /sys/devices/platform/alienware-wmi/hdmi/*
        - /sys/devices/platform/alienware-wmi/rgb_zones/*

plugs:
  alienware:
    interface: custom-device
    custom-device: alienware-wmi

parts:
  awc:
    plugin: rust
    source: https://github.com/a1ecbr0wn/alienware-wmi/archive/refs/tags/v1.0.4.tar.gz
    rust-path: ["alienware_cli"]

apps:
  awc:
    command: bin/awc
    plugs: [alienware]
