name: CI Build

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'feature/*'
    paths-ignore:
      - '*.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target=${{ matrix.TARGET }}
